# Generated by Django 4.2.3 on 2023-08-08 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_postreaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
        migrations.RemoveField(
            model_name='post',
            name='like_count',
        ),
    ]
